# DataAcomp Python Tracker

# 1. list

In [91]:
list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    # Positive indexing
# print(list[:4])  # [start, end-1] [1, 2, 3, 4]
# print(list[::3])   # [1, 4, 7]
# print(list[1::3])  #  [2, 5, 8]
# print(list[::4]) #  [1, 5, 9]
# print(list[::2]) #  [1, 3, 5, 7, 9]

    # Negative indexing
# print(list[:-4]) # [start, end-1] [1, 2, 3, 4, 5, 6 ]
# print(list[::-3])   # [10, 7, 4, 1]
# print(list[::-4]) # [10, 6, 2]
# print(list[::-2]) # [10, 8, 6, 4, 2]

# print(list[::-1]) # [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
print(list[0::]) # [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(list[::1]) # [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# print(list[2::]) # [3, 4, 5, 6, 7, 8, 9, 10]




[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [13]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# Adapt list areas
areas = ['hallway', hall, 'kitchen', kit, 'living room', liv, 'bedroom',  bed, 'bathroom', bath]

# Print areas
print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]


In [14]:
# area variables (in square meters)
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

# house information as list of lists
house = [["hallway", hall],
         ["kitchen", kit],
         ["living room", liv,],
         ["bedroom", bed],
         ["bathroom", bath]]

# Print out house
print(house)

# Print out the type of house
print(type(house))

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
<class 'list'>


# 2.Subsetting lists

In [16]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Print out second element from areas
print(areas[1]) # 11.25

# Print out last element from areas
print(areas[-1]) # 9.5

# Print out the area of the living room
print(areas[5]) # 20.0

# Create the areas list
print(areas[1:5]) # 11.25, 'kitchen', 18.0, 'living room']

print(areas[1::]) # [11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]
print(areas[::-1]) # [9.5, 'bathroom', 10.75, 'bedroom', 20.0, 'living room', 18.0, 'kitchen', 11.25, 'hallway']

print(areas[::-2]) # [9.5, 10.75, 20.0, 18.0, 11.25]

print(areas[::1]) # ['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]
print(areas[0::]) # ['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]

eat_sleep_area = sum([areas[3] + areas[-3]])
print(eat_sleep_area) # 28.75

11.25
9.5
20.0
[11.25, 'kitchen', 18.0, 'living room']
[11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]
[9.5, 'bathroom', 10.75, 'bedroom', 20.0, 'living room', 18.0, 'kitchen', 11.25, 'hallway']
[9.5, 10.75, 20.0, 18.0, 11.25]
['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]
['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 9.5]
28.75


In [19]:
# Create the areas list
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

# Use slicing to create downstairs
downstairs = areas[:6]

# Use slicing to create upstairs
upstairs = areas[-4:]

# Print out downstairs and upstairs
print(downstairs, upstairs)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0] ['bedroom', 10.75, 'bathroom', 9.5]


# 3.Manuypulating lists

In [98]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = x 

# By reference
print(x == y) # True
print(id(x), id(y))
print(x is y) # True
# By value

x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = x.copy()

print(x == y) # True
print(id(x), id(y))
print(x is y) # False



True
2617711049728 2617711049728
True
True
2617710744832 2617710581568
False


In [109]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

print(areas)

# Correct the bathroom area

print(areas[-1]) # 10.50
areas[-1] = 88888.50
print(areas)

del(areas[-4:-2]) # remove 2 elements from the list [poolhouse', 24.5]
print(areas)


['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]
15.45
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 88888.5]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 88888.5]


# Functions and Methods on lists

In [129]:
# Create lists first and second
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

# Paste together first and second: full
full = first + second
print(full) # [11.25, 18.0, 20.0, 10.75, 9.5]

# Sort full in descending order: full_sorted
full_sorted = sorted(full, reverse=True)
# Print out full_sorted
print(full_sorted) # [20.0, 18.0, 11.25, 10.75, 9.5]


full_sorted.reverse()
print(full_sorted) # [9.5, 10.75, 11.25, 18.0, 20.0]

[11.25, 18.0, 20.0, 10.75, 9.5]
[20.0, 18.0, 11.25, 10.75, 9.5]
[9.5, 10.75, 11.25, 18.0, 20.0]


# Numpy

In [136]:
# Import the numpy package as np
import numpy as np

# Create list baseball

baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Create a numpy array from baseball: np_baseball

np_baseball = np.array(baseball)

# Print out type of np_baseball

print(np_baseball) # <class 'numpy.ndarray'>

print(np_baseball is baseball) # False


[180 215 210 210 188 176 209 200]
False


In [142]:
import numpy as np
list_numpy = np.array([1, 2, 3, 4, 5])
list_python = [1, 2, 3, 4, 5]

print(list_numpy) # [1 2 3 4 5]

# sum numpy array 
x = list_numpy + list_python

# Sum 2 listes python 
list_python2 = [2, 4, 6, 8, 10]
y = list_python + list_python2

print(x) # [ 2  4  6  8 10]

print(y) # [1, 2, 3, 4, 5, 2, 4, 6, 8, 10]

[1 2 3 4 5]
[ 2  4  6  8 10]
[1, 2, 3, 4, 5, 2, 4, 6, 8, 10]


In [147]:
import numpy as np
x = [1, 4, 8, 10, 12]

np.mean(x) # 7.0
np.median(x) # 8.0



8.0

# Basic plots with Matplotlib

In [153]:
# import matplotlib.pyplot as plt

year = [1950, 1970, 1990, 2010, 2020, 2024]

pop = [2.519, 3.692, 5.263, 6.972, 8.509, 9.511]

# plt.plot(year, pop)

# plt.show()